### ISSUE TITLE
Invite instructor and TA to repo

### ISSUE THREAD

**Issue by ugurdogrusoz** [CS319-Group1G/1G.Super-Mario-Bros#2]

**Comment by ugurdogrusoz** [comment]
I didn't get an invitation?

**Comment by ahmetcandiroglu** [comment]
sir you seem as a collaborator

**Comment by ugurdogrusoz** [comment]
@ahmetcandiroglu Are you sure? How come I cannot change assignments, etc. Limited access?

**Comment by ahmetcandiroglu** [comment]
@ugurdogrusoz I guess it automatically gave you limited access. You now have admin rights
